version: 2.1

commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install

jobs:
  test_unit:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout 
      - install_deps
      - run:
          name: run tests
          command: |
            npm run --prefix src/test-unit


workflows:
  build-and-package:
    jobs:
      - test_unit