version: 2.1

jobs:
  sast:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install NodeJsScan
          command: |
            sudo apt update
            sudo apt install python3-pip
            pip3 install nodejsscan
      - run: 
           name: run NodeJsScan
           command: |
             nodejsscan -d ./



workflows:
  build-and-package:
    jobs:
      - codeanaly:
          