version: 2.1

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
         name: install dependencies
         command: |
             yarn --frozen-lockfile

workflows:
  build-and-packge:
    jobs:
      - ci-build
