version: 2.1

jobs:
  intergration-tests:
    docker:
      - image: circleci/node:lts
    environment: 
      APP_PORT: 4000
    steps:
      - checkout

workflows:
  build-and-packge:
    jobs:
      - intergration-tests
